version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_password
      POSTGRES_DB: project_database
    ports:
      - "5432:5432"
    volumes:
      - project_postgres:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: ["python", "server.py"]

volumes:
  project_postgres:
